from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"

GAME_JS = PUBLIC / "game.js"
CONSTANTS_JS = PUBLIC / "game" / "constants.js"
SESSION_JS = PUBLIC / "game" / "session.js"
GEMS_JS = PUBLIC / "game" / "gems.js"
OUT_JS = PUBLIC / "game.bundle.js"


def strip_exports(source: str) -> str:
    return re.sub(r"(?m)^\s*export\s+", "", source)


def strip_imports(source: str) -> str:
    source = re.sub(
        r"(?ms)^\s*import\s*\{.*?\}\s*from\s*\"\.\/game\/constants\.js\";\s*",
        "",
        source,
    )
    source = re.sub(
        r"(?ms)^\s*import\s*\{.*?\}\s*from\s*\"\.\/game\/session\.js\";\s*",
        "",
        source,
    )
    source = re.sub(
        r"(?ms)^\s*import\s*\{.*?\}\s*from\s*\"\.\/game\/gems\.js\";\s*",
        "",
        source,
    )
    return source


def main() -> None:
    constants = strip_exports(CONSTANTS_JS.read_text(encoding="utf-8")).strip()
    session = strip_exports(SESSION_JS.read_text(encoding="utf-8")).strip()
    gems = strip_exports(GEMS_JS.read_text(encoding="utf-8")).strip()
    game = strip_imports(GAME_JS.read_text(encoding="utf-8")).strip()

    output = "\n\n".join(
        [
            "/* Auto-generated by scripts/build_bundle.py. Do not edit directly. */",
            constants,
            session,
            gems,
            game,
            "",
        ]
    )

    OUT_JS.write_text(output, encoding="utf-8")
    print(f"Wrote {OUT_JS}")


if __name__ == "__main__":
    main()
